config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # See all tasks
  get 'tasks', to: 'tasks#index'

  # Create a task
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  # See details about one task
  get "tasks/:id", to: "tasks#show", as: :task

  # Update a task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"

  # Destroy a task
  delete "tasks/:id", to: "tasks#destroy", as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @tasks = Task.find(params[:id])
  end

  def new
    @task = Task.new # needed to instantiate the form_for
  end

  def create
    @task = Task.new(task_params)
    @task.save
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    # no need for app/views/tasks/destroy.html.erb
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="container">
    <body>
      <%= yield %>
    </body>
  </div>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Update une Tâche</h1>


  <%= simple_form_for(@task) do |f| %>
    <%= f.input :title %>
    <%= f.input :details %>
    <%= f.input :completed %>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>Hello my friend</h1>

  <ol>
    <% @tasks.each do |task| %>
      <li><%= link_to task.title, task_path(task.id) %> | <%= task.completed %> || <%= link_to "Delete",
              task_path(task.id),
              method: :delete,
              data: { confirm: "Are you sure?" } %></li>
    <% end %>
    <%= link_to "Create a new Task", tasks_new_path %>
  </ol>
</div>

app/views/tasks/new.html.erb
  <h1>Créer une Tâche</h1>

  <%= simple_form_for(@task) do |f| %>
    <%= f.input :title %>
    <%= f.input :details %>
    <%= f.input :completed %>
    <%= f.submit %>
  <% end %>

app/views/tasks/show.html.erb
<h2><%= @tasks.title %></h2>
<p><%= @tasks.details %></p>
<p><%= @tasks.completed %></p>
<p><%= link_to "Edit a Task", edit_task_path%> || <%= link_to "Delete",
            task_path(@tasks),
            method: :delete,
            data: { confirm: "Are you sure?" } %></p>
<p><%= link_to "Mes Tâches", tasks_path%> </p>